### ISSUE TITLE
support decompile APK (Android).

### ISSUE THREAD

**Issue by OVERPEY** [OpenGMK/GM8Decompiler#15]
could i use this to decompile  gamedata on an APK file ? if not please support that.

**Comment by skyfloogle** [comment]
To be precise: We support GameMaker versions 8.0 and 8.1, and that only had a Windows export. Android export wasn't added until Studio, and we don't support that.
There's Studio decompilers out there, though I don't know how well those support Android.

**Comment by OVERPEY** [comment]
Okay i got it now, thanks for helping.
